# Site settings
title: Trianimalia
email: matej.jirasek@me.com
description: "Taxonomy of triangulated animals. Art by Matěj Kašpar Jirásek"
baseurl: ""
url: "http://trianimalia.com"
twitter_username: mkj_is
github_username:  mkj-is

# Build settings
markdown: kramdown
permalink: "/:title/"
